global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "flux-api"
    static_configs:
      - targets:
          - "host.docker.internal:3000"

  - job_name: "flux-worker"
    static_configs:
      - targets:
          - "host.docker.internal:3001"
          